server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.13.129:3306/cloudLibrary
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:**/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
